"""baseline_phase_4_1

Revision ID: 70886515613a
Revises: 
Create Date: 2026-09-01 15:46:22.446388

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70886515613a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.String(length=64), nullable=False),
    sa.Column('business_date', sa.String(length=10), nullable=False),
    sa.Column('rule_id', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('actual_value', sa.String(length=255), nullable=True),
    sa.Column('threshold_value', sa.String(length=255), nullable=True),
    sa.Column('comparison', sa.String(length=255), nullable=True),
    sa.Column('message_code', sa.String(length=64), nullable=True),
    sa.Column('dataset_type', sa.String(length=32), nullable=False),
    sa.Column('ingestion_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_alert_id'), 'alerts', ['alert_id'], unique=True)
    op.create_index(op.f('ix_alerts_business_date'), 'alerts', ['business_date'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_ingestion_id'), 'alerts', ['ingestion_id'], unique=False)
    op.create_index(op.f('ix_alerts_rule_id'), 'alerts', ['rule_id'], unique=False)
    op.create_index(op.f('ix_alerts_severity'), 'alerts', ['severity'], unique=False)
    op.create_table('analyst_briefs',
    sa.Column('brief_id', sa.String(), nullable=False),
    sa.Column('business_date', sa.String(), nullable=False),
    sa.Column('dataset_type', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('requested_provider', sa.String(), nullable=True),
    sa.Column('actual_provider', sa.String(), nullable=True),
    sa.Column('fallback_used', sa.Boolean(), nullable=True),
    sa.Column('fallback_reason', sa.String(), nullable=True),
    sa.Column('provider', sa.String(), nullable=True),
    sa.Column('model', sa.String(), nullable=True),
    sa.Column('prompt_version', sa.String(), nullable=True),
    sa.Column('facts_version', sa.String(), nullable=True),
    sa.Column('rule_version', sa.String(), nullable=True),
    sa.Column('validator_version', sa.String(), nullable=True),
    sa.Column('provider_version', sa.String(), nullable=True),
    sa.Column('code_version', sa.String(), nullable=True),
    sa.Column('dataset_sha256', sa.String(), nullable=True),
    sa.Column('raw_response_hash', sa.String(), nullable=True),
    sa.Column('review_authentication_status', sa.String(), nullable=True),
    sa.Column('identity_verified', sa.Boolean(), nullable=True),
    sa.Column('executive_summary', sa.Text(), nullable=False),
    sa.Column('findings_json', sa.Text(), nullable=True),
    sa.Column('possible_causes_json', sa.Text(), nullable=True),
    sa.Column('recommended_actions_json', sa.Text(), nullable=True),
    sa.Column('unknowns_json', sa.Text(), nullable=True),
    sa.Column('evidence_ids_json', sa.Text(), nullable=True),
    sa.Column('rejection_reasons_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('brief_id')
    )
    op.create_index(op.f('ix_analyst_briefs_brief_id'), 'analyst_briefs', ['brief_id'], unique=False)
    op.create_index(op.f('ix_analyst_briefs_business_date'), 'analyst_briefs', ['business_date'], unique=False)
    op.create_table('daily_facts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.String(length=10), nullable=False),
    sa.Column('sales', sa.Float(), nullable=True),
    sa.Column('guests', sa.Integer(), nullable=True),
    sa.Column('avg_check', sa.Float(), nullable=True),
    sa.Column('labor_cost', sa.Float(), nullable=True),
    sa.Column('labor_ratio', sa.Float(), nullable=True),
    sa.Column('food_cost', sa.Float(), nullable=True),
    sa.Column('food_cost_ratio', sa.Float(), nullable=True),
    sa.Column('incoming_kg', sa.Float(), nullable=True),
    sa.Column('sold_kg', sa.Float(), nullable=True),
    sa.Column('service_kg', sa.Float(), nullable=True),
    sa.Column('waste_kg', sa.Float(), nullable=True),
    sa.Column('waste_ratio', sa.Float(), nullable=True),
    sa.Column('theory_end_kg', sa.Float(), nullable=True),
    sa.Column('actual_end_kg', sa.Float(), nullable=True),
    sa.Column('variance_kg', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('complaints', sa.Integer(), nullable=True),
    sa.Column('contribution', sa.Float(), nullable=True),
    sa.Column('contribution_ratio', sa.Float(), nullable=True),
    sa.Column('data_status', sa.String(length=32), nullable=False),
    sa.Column('dataset_type', sa.String(length=32), nullable=False),
    sa.Column('ingestion_id', sa.String(length=64), nullable=False),
    sa.Column('facts_version', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_facts_business_date'), 'daily_facts', ['business_date'], unique=False)
    op.create_index(op.f('ix_daily_facts_id'), 'daily_facts', ['id'], unique=False)
    op.create_index(op.f('ix_daily_facts_ingestion_id'), 'daily_facts', ['ingestion_id'], unique=False)
    op.create_table('daily_operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_date', sa.String(length=10), nullable=False),
    sa.Column('raw_date', sa.String(length=32), nullable=True),
    sa.Column('sales', sa.Float(), nullable=True),
    sa.Column('guests', sa.Integer(), nullable=True),
    sa.Column('labor_cost', sa.Float(), nullable=True),
    sa.Column('food_cost', sa.Float(), nullable=True),
    sa.Column('incoming_kg', sa.Float(), nullable=True),
    sa.Column('sold_kg', sa.Float(), nullable=True),
    sa.Column('service_kg', sa.Float(), nullable=True),
    sa.Column('waste_kg', sa.Float(), nullable=True),
    sa.Column('actual_end_kg', sa.Float(), nullable=True),
    sa.Column('theory_end_kg', sa.Float(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('complaints', sa.Integer(), nullable=True),
    sa.Column('dataset_type', sa.String(length=32), nullable=False),
    sa.Column('ingestion_id', sa.String(length=64), nullable=False),
    sa.Column('source_row', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_operations_business_date'), 'daily_operations', ['business_date'], unique=False)
    op.create_index(op.f('ix_daily_operations_id'), 'daily_operations', ['id'], unique=False)
    op.create_index(op.f('ix_daily_operations_ingestion_id'), 'daily_operations', ['ingestion_id'], unique=False)
    op.create_table('decision_actions',
    sa.Column('decision_id', sa.String(), nullable=False),
    sa.Column('brief_id', sa.String(), nullable=False),
    sa.Column('action_index', sa.Integer(), nullable=False),
    sa.Column('action_text', sa.Text(), nullable=False),
    sa.Column('owner_role', sa.String(), nullable=True),
    sa.Column('priority', sa.String(), nullable=True),
    sa.Column('approval_required', sa.Boolean(), nullable=True),
    sa.Column('decision_status', sa.String(), nullable=True),
    sa.Column('reviewer_role', sa.String(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('decision_id')
    )
    op.create_index(op.f('ix_decision_actions_brief_id'), 'decision_actions', ['brief_id'], unique=False)
    op.create_index(op.f('ix_decision_actions_decision_id'), 'decision_actions', ['decision_id'], unique=False)
    op.create_table('decision_audit_logs',
    sa.Column('log_id', sa.String(), nullable=False),
    sa.Column('brief_id', sa.String(), nullable=False),
    sa.Column('decision_id', sa.String(), nullable=True),
    sa.Column('previous_status', sa.String(), nullable=False),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('actor_role', sa.String(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('review_authentication_status', sa.String(), nullable=True),
    sa.Column('previous_hash', sa.String(), nullable=True),
    sa.Column('event_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_index(op.f('ix_decision_audit_logs_brief_id'), 'decision_audit_logs', ['brief_id'], unique=False)
    op.create_index(op.f('ix_decision_audit_logs_log_id'), 'decision_audit_logs', ['log_id'], unique=False)
    op.create_table('evidence_index',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_type', sa.String(length=32), nullable=False),
    sa.Column('business_date', sa.String(length=10), nullable=True),
    sa.Column('rule_id', sa.String(length=32), nullable=True),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('file_sha256', sa.String(length=64), nullable=False),
    sa.Column('dataset_sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_index_evidence_id'), 'evidence_index', ['evidence_id'], unique=True)
    op.create_index(op.f('ix_evidence_index_id'), 'evidence_index', ['id'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ingestion_id', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('dataset_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('valid_row_count', sa.Integer(), nullable=False),
    sa.Column('blocked_row_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('code_version', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_id'), 'ingestion_runs', ['id'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_ingestion_id'), 'ingestion_runs', ['ingestion_id'], unique=True)
    op.create_index(op.f('ix_ingestion_runs_source_sha256'), 'ingestion_runs', ['source_sha256'], unique=False)
    op.create_table('period_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.String(length=64), nullable=False),
    sa.Column('rule_id', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('baseline_start', sa.String(length=10), nullable=True),
    sa.Column('baseline_end', sa.String(length=10), nullable=True),
    sa.Column('target_start', sa.String(length=10), nullable=False),
    sa.Column('target_end', sa.String(length=10), nullable=False),
    sa.Column('metric_name', sa.String(length=64), nullable=True),
    sa.Column('baseline_value', sa.Float(), nullable=True),
    sa.Column('target_value', sa.Float(), nullable=True),
    sa.Column('comparison', sa.String(length=255), nullable=True),
    sa.Column('dataset_type', sa.String(length=32), nullable=False),
    sa.Column('ingestion_id', sa.String(length=64), nullable=False),
    sa.Column('evidence_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_period_alerts_alert_id'), 'period_alerts', ['alert_id'], unique=True)
    op.create_index(op.f('ix_period_alerts_id'), 'period_alerts', ['id'], unique=False)
    op.create_index(op.f('ix_period_alerts_ingestion_id'), 'period_alerts', ['ingestion_id'], unique=False)
    op.create_index(op.f('ix_period_alerts_rule_id'), 'period_alerts', ['rule_id'], unique=False)
    op.create_index(op.f('ix_period_alerts_severity'), 'period_alerts', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_period_alerts_severity'), table_name='period_alerts')
    op.drop_index(op.f('ix_period_alerts_rule_id'), table_name='period_alerts')
    op.drop_index(op.f('ix_period_alerts_ingestion_id'), table_name='period_alerts')
    op.drop_index(op.f('ix_period_alerts_id'), table_name='period_alerts')
    op.drop_index(op.f('ix_period_alerts_alert_id'), table_name='period_alerts')
    op.drop_table('period_alerts')
    op.drop_index(op.f('ix_ingestion_runs_source_sha256'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_ingestion_id'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_evidence_index_id'), table_name='evidence_index')
    op.drop_index(op.f('ix_evidence_index_evidence_id'), table_name='evidence_index')
    op.drop_table('evidence_index')
    op.drop_index(op.f('ix_decision_audit_logs_log_id'), table_name='decision_audit_logs')
    op.drop_index(op.f('ix_decision_audit_logs_brief_id'), table_name='decision_audit_logs')
    op.drop_table('decision_audit_logs')
    op.drop_index(op.f('ix_decision_actions_decision_id'), table_name='decision_actions')
    op.drop_index(op.f('ix_decision_actions_brief_id'), table_name='decision_actions')
    op.drop_table('decision_actions')
    op.drop_index(op.f('ix_daily_operations_ingestion_id'), table_name='daily_operations')
    op.drop_index(op.f('ix_daily_operations_id'), table_name='daily_operations')
    op.drop_index(op.f('ix_daily_operations_business_date'), table_name='daily_operations')
    op.drop_table('daily_operations')
    op.drop_index(op.f('ix_daily_facts_ingestion_id'), table_name='daily_facts')
    op.drop_index(op.f('ix_daily_facts_id'), table_name='daily_facts')
    op.drop_index(op.f('ix_daily_facts_business_date'), table_name='daily_facts')
    op.drop_table('daily_facts')
    op.drop_index(op.f('ix_analyst_briefs_business_date'), table_name='analyst_briefs')
    op.drop_index(op.f('ix_analyst_briefs_brief_id'), table_name='analyst_briefs')
    op.drop_table('analyst_briefs')
    op.drop_index(op.f('ix_alerts_severity'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_rule_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_ingestion_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_business_date'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_id'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
